### ISSUE TITLE
ValueError: Cannot feed value of shape (0,) for Tensor 'Cast:0', which has shape '(?, 512, 512, 3)'

### ISSUE THREAD

**Issue by yongshuo-Z** [anonymoussss/IDRiD_sub1_EX#1]
hello!
When I run your code. I got the following error:

#----------------------------------------------------------------------------------
Traceback (most recent call last):
  File "unet.py", line 319, in <module>
    tf.app.run()
  File "/home/ilab/anaconda3/envs/seg36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "unet.py", line 246, in main
    tra_positive_prob, train_err, _ = sess.run([train_positive_prob, train_loss_op,train_op], feed_dict=feed_dict)
  File "/home/ilab/anaconda3/envs/seg36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ilab/anaconda3/envs/seg36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'Cast:0', which has shape '(?, 512, 512, 3)'
#----------------------------------------------------------------------------------------------------

I don't know what to do with that. Please help... By the way, what's the proper version of the tensorlayer and tensorflow?

**Comment by anonymoussss** [comment]
@yongshuo-Z 
Probably because the data was read unsuccessfully, the reasons may be path inconsistency, format inconsistency and so on. It is recommended that you debug the data reading part to check whether the data is read correctly.
Actually, I forgot what version of the code I ran for the first time. But tf1.14 and tl1.11 can be used recently.

**Comment by yongshuo-Z** [comment]
> @yongshuo-Z
> Probably because the data was read unsuccessfully, the reasons may be path inconsistency, format inconsistency and so on. It is recommended that you debug the data reading part to check whether the data is read correctly.
> Actually, I forgot what version of the code I ran for the first time. But tf1.14 and tl1.11 can be used recently.

Thanks for your answer. The code now works well with tf 1.14.0.
